stages:
  - test

test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker run --rm -v "$CI_PROJECT_DIR":/app -w /app golang:1.23.2 go mod download
  script:
    - docker run --rm -v "$CI_PROJECT_DIR":/app -w /app golang:1.23.2 go test ./... -v -cover
    - docker run --rm -v "$CI_PROJECT_DIR":/app -w /app golang:1.23.2 go vet ./...
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
  coverage: '/coverage: \d+.\d+% of statements/'
